In [17]:
import csv
import json

import pandas as pd

In [18]:
result = json.load(open('result.json'))

In [40]:
data = []
with open('annotated.csv') as f:
    reader = list(csv.reader(f, delimiter=',', quotechar='\"'))[1:-1]
    
    inp = {}
    for i, row in enumerate(reader):
        inp['domain'] = result[i]['domain']
        result[i]['results'] = row[3:10]
        
        data.append({
            'domain': result[i]['domain'],
#             'model': result[i]['domain'].split('_')[-1],
            'number': 1 if row[3].lower().strip() == 's' else 0,
            'entity': 1 if row[4].lower().strip() == 's' else 0,
            'word': 1 if row[5].lower().strip() == 's' else 0,
            'context': 1 if row[6].lower().strip() == 's' else 0,
            'ncheckable': 1 if row[7].lower().strip() == 's' else 0,
            'other': 1 if row[8].lower().strip() == 's' else 0,
            'fluency': 1 if row[9].lower().strip() == 's' else 0,
        })
        
data = pd.DataFrame(data)
a = data.groupby(['domain']).sum() / data.groupby(['domain']).count()
a.round(4)

,number,entity,word,context,ncheckable,other,fluency
domain,,,,,,,
botsdobem_bertimbau,0.7000,0.4077,0.0077,0.5077,0.1846,0.1538,0.2077
botsdobem_gportuguese,0.3923,0.3308,0.0000,0.4692,0.2538,0.0462,0.0462
botsdobem_mbart,0.1000,0.0615,0.0231,0.3000,0.0385,0.0308,0.1308
botsdobem_mt5,0.4538,0.2538,0.0154,0.7077,0.2077,0.0154,0.5154
botsdobem_synthetic_bertimbau,0.5615,0.1615,0.0308,0.0154,0.0077,0.4615,0.0077
botsdobem_synthetic_gportuguese,0.2231,0.0615,0.0231,0.0923,0.0231,0.0385,0.0154
botsdobem_synthetic_mbart,0.2692,0.0154,0.0308,0.0923,0.0231,0.0462,0.0154
botsdobem_synthetic_mt5,0.3154,0.0077,0.0231,0.0231,0.0000,0.0462,0.0154
gold,0.0077,0.0077,0.0154,0.0077,0.0000,0.0154,0.0077

In [44]:
data = []
with open('annotated.csv') as f:
    reader = list(csv.reader(f, delimiter=',', quotechar='\"'))[1:-1]
    
    inp = {}
    for i, row in enumerate(reader):
        inp['domain'] = result[i]['domain']
        result[i]['results'] = row[3:10]
        
        if 'synthetic' in inp['domain'] or 'gold' in inp['domain']:
            data.append({
                'model': result[i]['domain'].split('_')[-1],
                'number': 1 if row[3].lower().strip() == 's' else 0,
                'entity': 1 if row[4].lower().strip() == 's' else 0,
                'word': 1 if row[5].lower().strip() == 's' else 0,
                'context': 1 if row[6].lower().strip() == 's' else 0,
                'ncheckable': 1 if row[7].lower().strip() == 's' else 0,
                'fluency': 1 if row[9].lower().strip() == 's' else 0,
                'other': 1 if row[8].lower().strip() == 's' else 0,
            })
        
data = pd.DataFrame(data)
a = data.groupby(['model']).sum() #/ data.groupby(['model']).count()
a.round(3)

             number  entity  word  context  ncheckable  fluency  other
model
bertimbau        73      21     4        2           1        1     60
gold              1       1     2        1           0        1      2
gportuguese      29       8     3       12           3        2      5
mbart            35       2     4       12           3        2      6
mt5              41       1     3        3           0        2      6

In [27]:
data.groupby(['domain']).count()

,number,entity,word,context,ncheckable,other,fluency
domain,,,,,,,
botsdobem_bertimbau,130,130,130,130,130,130,130
botsdobem_gportuguese,130,130,130,130,130,130,130
botsdobem_mbart,130,130,130,130,130,130,130
botsdobem_mt5,130,130,130,130,130,130,130
botsdobem_synthetic_bertimbau,130,130,130,130,130,130,130
botsdobem_synthetic_gportuguese,130,130,130,130,130,130,130
botsdobem_synthetic_mbart,130,130,130,130,130,130,130
botsdobem_synthetic_mt5,130,130,130,130,130,130,130
gold,130,130,130,130,130,130,130